name: VPS Auto-Loop Trigger
on:
  push:
    branches: [main]
    paths:
      - '.backup/autovps.zip'

jobs:
  restart-relay:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ Dispatching New Instance
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
          -d '{"event_type": "create-vps"}'
