name: Auto Start VPS Loop

on:
  push:
    branches: [main]
    paths:
      - '.backup/autovps.zip' # Triggers when backup is pushed
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ Trigger Next VPS Session
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          -d '{"event_type": "create-vps", "client_payload": {"backup": "true"}}'

